### model
model_name_or_path: /data/nlp-data/wenyuan/llm/Qwen2-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### ddp
ddp_timeout: 180000000

### dataset
dataset: combined_remaining_train_0717_split_train, combined_remaining_train_0717_split_dev
template: qwen
cutoff_len: 2048
max_samples: 10000000
overwrite_cache: true
preprocessing_num_workers: 32

### output
output_dir: saves/qwen2_7b_xhs_benchmarks/AAAI/0718_multi_xhs_inst_qwen7b/lora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_steps: 0
fp16: true

### eval
# val_size: 0.1
val_size: 19557
per_device_eval_batch_size: 4
evaluation_strategy: steps
eval_steps: 500
